import React,{useEffect,useRef,useState}from'react';
import{Canvas,useFrame,useThree}from'@react-three/fiber';
import*as THREE from'three';
import'./city3d.css';
const buildings=[['FREE',-45,-30,26,12,22],['TRIAL',42,-38,34,16,26],['GO',-58,35,46,22,32],['PLUS',35,48,58,28,40],['PRO',92,5,76,38,50],['LUXURY',-105,82,100,50,62]];
function Player({office=false,onEnter}){const{camera}=useThree();const keys=useRef({});const touch=useRef({x:0,y:0,lookX:0,lookY:0,run:false,enter:false});const yaw=useRef(0),pitch=useRef(0),lastEnter=useRef(false);useEffect(()=>{camera.position.set(0,2,120);const d=e=>keys.current[e.code]=1,u=e=>keys.current[e.code]=0;window.addEventListener('keydown',d);window.addEventListener('keyup',u);return()=>{window.removeEventListener('keydown',d);window.removeEventListener('keyup',u)}},[camera]);useFrame((_,dt)=>{yaw.current-=touch.current.lookX;pitch.current=THREE.MathUtils.clamp(pitch.current-touch.current.lookY,-1.2,1.2);touch.current.lookX=touch.current.lookY=0;camera.rotation.set(pitch.current,yaw.current,0,'YXZ');const k=keys.current;let f=(k.KeyW?1:0)-(k.KeyS?1:0)-touch.current.y,s=(k.KeyD?1:0)-(k.KeyA?1:0)+touch.current.x;const v=new THREE.Vector3(s,0,-f);if(v.lengthSq()){v.normalize().applyAxisAngle(new THREE.Vector3(0,1,0),yaw.current);const sp=touch.current.run||k.ShiftLeft?9:5;camera.position.addScaledVector(v,sp*dt)}camera.position.y=2;const enter=k.KeyE||touch.current.enter;if(!office&&enter&&!lastEnter.current&&onEnter)onEnter();lastEnter.current=enter});return <Touch input={touch}/>}
function Touch({input}){const joy=useRef(),knob=useRef(),look=useRef();useEffect(()=>{const j=joy.current,k=knob.current,l=look.current;let jid=null,lid=null,last=null;const jm=e=>{e.preventDefault();if(jid===null)jid=e.pointerId;const r=j.getBoundingClientRect();let x=e.clientX-r.left-r.width/2,y=e.clientY-r.top-r.height/2,m=46,n=Math.hypot(x,y)||1;if(n>m){x=x/n*m;y=y/n*m}input.current.x=x/m;input.current.y=y/m;k.style.transform=`translate(${x}px,${y}px)`};const je=e=>{if(e.pointerId===jid){jid=null;input.current.x=input.current.y=0;k.style.transform='translate(0,0)'}};const ls=e=>{if(e.pointerType==='touch'){lid=e.pointerId;last={x:e.clientX,y:e.clientY};l.setPointerCapture?.(e.pointerId)}};const lm=e=>{if(e.pointerId===lid&&last){input.current.lookX+=(e.clientX-last.x)*.004;input.current.lookY+=(e.clientY-last.y)*.003;last={x:e.clientX,y:e.clientY}}};const le=()=>{lid=null;last=null};j.addEventListener('pointerdown',jm);j.addEventListener('pointermove',jm);j.addEventListener('pointerup',je);j.addEventListener('pointercancel',je);l.addEventListener('pointerdown',ls);l.addEventListener('pointermove',lm);l.addEventListener('pointerup',le);l.addEventListener('pointercancel',le);return()=>{j.removeEventListener('pointerdown',jm);j.removeEventListener('pointermove',jm);j.removeEventListener('pointerup',je);j.removeEventListener('pointercancel',je);l.removeEventListener('pointerdown',ls);l.removeEventListener('pointermove',lm);l.removeEventListener('pointerup',le);l.removeEventListener('pointercancel',le)}},[input]);return <div className="mobile-controls"><div ref={look} className="look-zone"/><div ref={joy} className="joystick"><div ref={knob} className="joystick-knob"/></div><button className="run-button" onPointerDown={()=>input.current.run=true} onPointerUp={()=>input.current.run=false}>БЕГАТЬ</button><button className="enter-button" onPointerDown={()=>input.current.enter=true} onPointerUp={()=>input.current.enter=false}>ВХОДИТЬ</button></div>}
function Buildings(){return <>{buildings.map(([name,x,y,w,h,d])=><group key={name} position={[x,h/2,y]}><mesh><boxGeometry args={[w,h,d]}/><meshStandardMaterial color="#edf1ee" roughness={.7}/></mesh><mesh position={[0,h/2+.5,0]}><boxGeometry args={[w*.9,.8,d*.85]}/><meshStandardMaterial color="#83999d"/></mesh></group>)}</>}
function Scene({office,onEnter}){return <Canvas dpr={[1,1.5]} camera={{position:[0,2,120],fov:70}}><color attach="background" args={['#eef2ef']}/><ambientLight intensity={2}/><directionalLight position={[50,100,30]} intensity={3}/><mesh rotation={[-Math.PI/2,0,0]}><planeGeometry args={[320,320]}/><meshStandardMaterial color="#dce3df"/></mesh>{office?null:<Buildings/>}<Player office={office} onEnter={onEnter}/></Canvas>}
function App(){const[office,setOffice]=useState(false);return <div className="city-core"><Scene office={office} onEnter={()=>setOffice(true)}/>{office&&<button className="back-city" onClick={()=>setOffice(false)}>← ГОРОД</button>}<div className="city-hud"><b>ГОРОД КОМПАНИЙ ИСКУССТВЕННОГО ИНТЕЛЛЕКТА</b><span>ДЖОЙСТИК + СВАЙП · WASD + МЫШЬ</span></div></div>}
export default App;
